[package]
name = "connie"
version = "0.1.0"
edition = "2021"

[workspace]
members = []



[dependencies]
#common_lib = { path = "../common_lib/" }
#tcp = { path = "../protocol/tcp/" }
clap = { version = "4.5.23", features = ["cargo"] }
ratatui = { version = "=0.23.0", features = ["all-widgets"] }
